[package]
name = "famllib"
version = "0.1.11"
edition = "2024"
publish = false

[lib]
name = "famllib"
crate-type = ["cdylib", "staticlib"]

[dependencies]
faml = { path = "../faml" }

[build-dependencies]
cbindgen = "0.29.0"
